### ISSUE TITLE
Installation failed ?

### ISSUE THREAD

**Issue by domainController** [phra/crosser#15]
My X200 thinkpad has 32-bit CPU architecture. Furthermore can't upgrade node beyond version 10.

Can I still try to get familiar with your tool and the whole puppeteer world  or shall forget about it given all below packages are not supported ?

![crosser](https://user-images.githubusercontent.com/58897196/106258612-f76ec880-6215-11eb-8019-e726de8febbc.png)

Thanks

**Comment by domainController** [comment]
Is there any file to edit 

![crosser2](https://user-images.githubusercontent.com/58897196/106261769-f3dd4080-6219-11eb-8d62-07b174c5cda9.png)

**Comment by domainController** [comment]
Do I have to edit a file to launch this chrome specific version succesfully ? 

Can I add my own chromium-browser path in some config file somewhere instead ?

Or did I do something wrong as I get this "Syntax error: Unterminated quoted string" ?



![crosser2](https://user-images.githubusercontent.com/58897196/106261944-2e46dd80-621a-11eb-848d-846d5933652b.png)

**Comment by phra** [comment]
unfortunately, it seems that chromium is not supported on 32-bit anymore so I don't think it's possible to make it work. (https://github.com/puppeteer/puppeteer/issues/5665)
